name: Docs

on:
  schedule:
    # Once a month to ensure future
    # b3sum and alpine versions are tested
    - cron: "14 0 * * 1"
  push:
    tags-ignore:
      - '**'
    branches:
      - main
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: bermi/snapdir:latest
      - name: Verify docs
        run: |
          ./utils/verify-docs.sh
