name: Integration Tests
on:
  schedule:
    # Once a month to ensure future
    # b3sum versions are tested
    - cron: "2 0 * * 1"
  # Only when pushing to main branch
  push:
    branches:
      - main
defaults:
  run:
    shell: bash
env:
  SNAPDIR_B2_STORE_TEST_BUCKET: bermilabs-test-bucket
  SNAPDIR_B2_STORE_APPLICATION_KEY_ID: ${{ secrets.SNAPDIR_B2_STORE_APPLICATION_KEY_ID }}
  SNAPDIR_B2_STORE_APPLICATION_KEY: ${{ secrets.SNAPDIR_B2_STORE_APPLICATION_KEY }}
  SNAPDIR_S3_STORE_TEST_BUCKET: snapdir-test-bucket
  SNAPDIR_AWS_ACCESS_KEY_ID: ${{ secrets.SNAPDIR_AWS_ACCESS_KEY_ID}}
  SNAPDIR_AWS_SECRET_ACCESS_KEY: ${{ secrets.SNAPDIR_AWS_SECRET_ACCESS_KEY}}

jobs:
  b2:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip
          sudo wget -q "https://github.com/BLAKE3-team/BLAKE3/releases/download/1.3.1/b3sum_linux_x64_bin" -O /usr/local/bin/b3sum
          sudo chmod +x /usr/local/bin/b3sum
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: b2 integration test
        run: |
          ./snapdir-b2-store test --store b2://$SNAPDIR_B2_STORE_TEST_BUCKET
  s3:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip
          sudo wget -q "https://github.com/BLAKE3-team/BLAKE3/releases/download/1.3.1/b3sum_linux_x64_bin" -O /usr/local/bin/b3sum
          sudo chmod +x /usr/local/bin/b3sum
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: s3 integration test
        run: |
          docker run \
            -it \
            --rm \
            -e SNAPDIR_S3_STORE_TEST_BUCKET \
            -e SNAPDIR_AWS_ACCESS_KEY_ID \
            -e SNAPDIR_AWS_SECRET_ACCESS_KEY \
            -v $(pwd)/snapdir-manifest:/usr/bin/snapdir-manifest \
            -v $(pwd)/snapdir:/usr/bin/snapdir \
            -v $(pwd)/snapdir-s3-store:/usr/bin/snapdir-s3-store \
            -v $(pwd)/snapdir-file-store:/usr/bin/snapdir-file-store \
            -v $(pwd)/snapdir-test:/usr/bin/snapdir-test \
            -v /usr/local/bin/b3sum:/usr/bin/b3sum
            --entrypoint /bin/bash \
            amazon/aws-cli \
            -c "snapdir-s3-store test --store s3://$SNAPDIR_S3_STORE_TEST_BUCKET"