name: Integration Tests
on:
  schedule:
    # Once a month to ensure future
    # b3sum versions are tested
    - cron: "2 0 * * 1"
  # Only when pushing to main branch
  push:
    branches:
      - main
defaults:
  run:
    shell: bash
env:
  SNAPDIR_B2_STORE_TEST_BUCKET: bermilabs-test-bucket
  SNAPDIR_B2_STORE_APPLICATION_KEY_ID: ${{ secrets.SNAPDIR_B2_STORE_APPLICATION_KEY_ID }}
  SNAPDIR_B2_STORE_APPLICATION_KEY: ${{ secrets.SNAPDIR_B2_STORE_APPLICATION_KEY }}

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          sudo wget -q "https://github.com/BLAKE3-team/BLAKE3/releases/download/1.3.1/b3sum_linux_x64_bin" -O /usr/local/bin/b3sum
          sudo chmod +x /usr/local/bin/b3sum
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Linux integration tests
        run: |
          ./snapdir-test integration

  integration-tests-macos:
    runs-on: macos-latest
    timeout-minutes: 5
    steps:
      - name: Install dependencies
        run: |
          brew install coreutils b3sum bash
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: macOS integration tests
        run: |
          ./snapdir-test integration
