name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  docker-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: bermi/snapdir:latest , bermi/snapdir:${{ env.GITHUB_SHA }} , bermi/snapdir:${{ github.event.release.tag_name }}

  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    needs: docker-release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            snapdi*
            LICENSE
            README.md
            docs
