name: sqlite3 catalog
on:
  schedule:
    # Once a month to ensure future
    # aws cli versions are tested
    - cron: "1 0 * * 1"
  # Only when pushing to main branch
  push:
    tags-ignore:
      - '**'
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  s3:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget sqlite3
          sudo wget -q "https://github.com/BLAKE3-team/BLAKE3/releases/download/1.3.1/b3sum_linux_x64_bin" -O /usr/local/bin/b3sum
          sudo chmod +x /usr/local/bin/b3sum
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: tests
        run: |
          ./snapdir-sqlite3-catalog test
          SNAPDIR_CATALOG=sqlite3 ./snapdir test
