name: Verify
on:
  schedule:
    # Once a month to ensure future
    # b3sum versions are tested
    - cron: "13 0 * * 1"
  push:
  pull_request:
defaults:
  run:
    shell: bash
jobs:
  linting:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck shfmt
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: shellcheck
        run: |
          find . -maxdepth 1 -name "snapdir*" | xargs shellcheck
      - name: checking format
        run: |
          find . -maxdepth 1 -name "snapdir*" | xargs shfmt -w -s
          git diff --exit-code

  test-ubuntu-latest:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          sudo wget -q "https://github.com/BLAKE3-team/BLAKE3/releases/download/1.3.1/b3sum_linux_x64_bin" -O /usr/local/bin/b3sum
          sudo chmod +x /usr/local/bin/b3sum
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Test snapdir
        run: |
          ./snapdir-test

  test-macos:
    runs-on: macos-latest
    timeout-minutes: 5
    steps:
      - name: Install dependencies
        run: |
          brew install coreutils b3sum bash
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Test snapdir
        run: |
          ./snapdir-test
